name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

# for building the app
env:
  DB_TYPE: 'sqlite'
  DB_DATABASE: ':memory:'
  DB_SYNCHRONIZE: 'true'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  main:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          cache: 'npm'

      # - run: npx nx-cloud start-ci-run

      - run: npm ci

      - uses: nrwl/nx-set-shas@v4

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - run: npx nx affected -t lint test
      - run: npx nx affected -t build --exclude=app
      - run: npm install sqlite3 --save 
      - run: npm run build

      - run: npx nx affected --parallel 1 -t e2e-ci

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: dist/.playwright/apps/
          retention-days: 30
